In [1]:
# Reference: https://pdfs.semanticscholar.org/7824/11081e754b72da6565c41f3904de843b31d1.pdf

In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
problema = "10 estados"

Acoes cardinais (N ^, S !, L >, O <). Na linha Det as acoes sai deterministicas. Na linha prob as acoes resultam com 0.5 de chance ir ou ficar parado. Custo por ação = 1 

Prob [[1, 2, 3, 4, 5],

Det.  [6, 7, 8, 9, 10]]

s0 = 1
G = 5

In [4]:
states = [0,1,2,3,4,5,6,7,8,9] # estados
actions = [0,1,2,3] # 0 norte, 1 sul, 2 leste, 3 oeste (N ^, S !, L >, O <)

In [5]:
N_STATES = len(states)
N_ACTIONS = len(actions)

In [6]:
P = np.zeros((N_STATES, N_ACTIONS, N_STATES))  # transition probability
R = np.zeros((N_STATES, N_ACTIONS, N_STATES))  # rewards

In [7]:
# 0 norte, 1 sul, 2 leste, 3 oeste 
# P(s, a, s_), 
#em que a = [0, 1, 2, 3] -> (N ^, S !, L >, O <)

#s=0, s_[1,2]
P[0, 1, 5] = 0.5 #ir Pra sul
P[0, 1, 0] = 0.5 #ficar Parado qdo vai Pra sul
P[0, 2, 1] = 0.5 #ir Pra leste
P[0, 2, 0] = 0.5 #ficar Parada na acao de ir Pra leste

#s=1, s_[6, 2, 0]
P[1, 1, 6] = 0.5 #ir Pra sul
P[1, 1, 1] = 0.5 #ficar Parado qdo vai Pra sul
P[1, 2, 2] = 0.5 #ir Pra leste
P[1, 2, 1] = 0.5 #ficar Parada na acao de ir Pra leste
P[1, 3, 0] = 0.5 #ir Pra oeste
P[1, 3, 1] = 0.5 #ficar Parada na acao de ir Pra oeste

#s=2, s_[7, 3, 1]
P[2, 1, 7] = 0.5 #ir Pra sul
P[2, 1, 2] = 0.5 #ficar Parado qdo vai Pra sul
P[2, 2, 3] = 0.5 #ir Pra leste
P[2, 2, 2] = 0.5 #ficar Parada na acao de ir Pra leste
P[2, 3, 1] = 0.5 #ir Pra oeste
P[2, 3, 2] = 0.5 #ficar Parada na acao de ir Pra oeste


#s=3, s_[8, 4, 2]
P[3, 1, 8] = 0.5 #ir Pra sul
P[3, 1, 3] = 0.5 #ficar Parado qdo vai Pra sul
P[3, 2, 4] = 0.5 #ir Pra leste
P[3, 2, 3] = 0.5 #ficar Parada na acao de ir Pra leste
P[3, 3, 2] = 0.5 #ir Pra oeste
P[3, 3, 3] = 0.5 #ficar Parada na acao de ir Pra oeste

#s=4, s_[4]
P[4, 0, 4] = 0 #nao sair, Pois é a meta
P[4, 1, 4] = 0 #nao sair, Pois é a meta
P[4, 2, 4] = 0 #nao sair, Pois é a meta
P[4, 3, 4] = 0 #nao sair, Pois é a meta


#s=5, s_[0, 6]
P[5, 0, 0] = 1 #ir Pra norte
P[5, 2, 6] = 1 #ir Pra leste

#s=6, s_[1, 5, 7]
P[6, 0, 1] = 1 #ir Pra norte
P[6, 3, 5] = 1 #ir Pra oeste
P[6, 2, 7] = 1 #ir Pra leste

#s=7, s_[2, 6, 8]
P[7, 0, 2] = 1 #ir Pra norte
P[7, 3, 6] = 1 #ir Pra oeste
P[7, 2, 8] = 1 #ir Pra leste

#s=8, s_[3, 7, 9]
P[8, 0, 3] = 1 #ir Pra norte
P[8, 3, 7] = 1 #ir Pra oeste
P[8, 2, 9] = 1 #ir Pra leste


#s=9, s_[4, 8]
P[9, 0, 4] = 1 #ir Pra norte
P[9, 3, 8] = 1 #ir Pra oeste


In [8]:
# 0 norte, 1 sul, 2 leste, 3 oeste 
# R(s, a, s_), 
#em que a = [0, 1, 2, 3] -> (N ^, S !, L >, O <)

#s=0, s_[1,2]
R[0, 1, 5] = 1 #ir Pra sul
R[0, 1, 0] = 1 #ficar Parado qdo vai Pra sul
R[0, 2, 1] = 1 #ir Pra leste
R[0, 2, 0] = 1 #ficar Parada na acao de ir Pra leste

#s=1, s_[6, 2, 0]
R[1, 1, 6] = 1 #ir Pra sul
R[1, 1, 1] = 1 #ficar Parado qdo vai Pra sul
R[1, 2, 2] = 1 #ir Pra leste
R[1, 2, 1] = 1 #ficar Parada na acao de ir Pra leste
R[1, 3, 0] = 1 #ir Pra oeste
R[1, 3, 1] = 1 #ficar Parada na acao de ir Pra oeste

#s=2, s_[7, 3, 1]
R[2, 1, 7] = 1 #ir Pra sul
R[2, 1, 2] = 1 #ficar Parado qdo vai Pra sul
R[2, 2, 3] = 1 #ir Pra leste
R[2, 2, 2] = 1 #ficar Parada na acao de ir Pra leste
R[2, 3, 1] = 1 #ir Pra oeste
R[2, 3, 2] = 1 #ficar Parada na acao de ir Pra oeste


#s=3, s_[8, 4, 2]
R[3, 1, 8] = 1 #ir Pra sul
R[3, 1, 3] = 1 #ficar Parado qdo vai Pra sul
R[3, 2, 4] = 1 #ir Pra leste
R[3, 2, 3] = 1 #ficar Parada na acao de ir Pra leste
R[3, 3, 2] = 1 #ir Pra oeste
R[3, 3, 3] = 1 #ficar Parada na acao de ir Pra oeste

#s=4, s_[4]
R[4, 0, 4] = 0 #nao sair, Pois é a meta
R[4, 1, 4] = 0 #nao sair, Pois é a meta
R[4, 2, 4] = 0 #nao sair, Pois é a meta
R[4, 3, 4] = 0 #nao sair, Pois é a meta


#s=5, s_[0, 6]
R[5, 0, 0] = 1 #ir Pra norte
R[5, 2, 6] = 1 #ir Pra leste

#s=6, s_[1, 5, 7]
R[6, 0, 1] = 1 #ir Pra norte
R[6, 3, 5] = 1 #ir Pra oeste
R[6, 2, 7] = 1 #ir Pra leste

#s=7, s_[2, 6, 8]
R[7, 0, 2] = 1 #ir Pra norte
R[7, 3, 6] = 1 #ir Pra oeste
R[7, 2, 8] = 1 #ir Pra leste

#s=8, s_[3, 7, 9]
R[8, 0, 3] = 1 #ir Pra norte
R[8, 3, 7] = 1 #ir Pra oeste
R[8, 2, 9] = 1 #ir Pra leste


#s=9, s_[4, 8]
R[9, 0, 4] = 1 #ir Pra norte
R[9, 3, 8] = 1 #ir Pra oeste


In [9]:
H = np.random.rand(N_STATES)

In [10]:
H

array([0.54697248, 0.36854328, 0.72520768, 0.04199925, 0.41565655,
       0.35852389, 0.83956958, 0.16910188, 0.76854216, 0.11365863])

In [11]:
def prioritized_sweeping(MDP, R, epsilon, gamma):
       
    list_V = []
    list_policy = []
    numIter = 0
    #1- inicializa V0 arbitrariamente
    V = np.zeros(N_STATES)
    #2- inicializa H0 arbitrariamente
    H = np.random.rand(N_STATES)
    policy = np.zeros(N_STATES)
    epoca =1

    #3. faca para toda iteracao k > 0
    while True:
        print('****** Epoca: ', epoca)
        Vold = V.copy()
    
        #Parte A: escolha estado com maior prioridade: 
        s_k = np.argmax(H)
        value_s_k = max(H)
        
        #Parte B: aplica operador de Bellman em sk e mantem o valor para os outros estados s != sk pertencentes a S:
        # Vk+1(s) = Vk(s)
        Q = []
        q_best = 10000000
        for a in (i for i, val in enumerate(MDP[s_k]) if np.count_nonzero(val) > 0): # a = MDP.shape[1]
            q_sa = sum(MDP[s_k][a][s_] * (R[s_k][a][s_] + (Vold[s_] * gamma)) for s_ in range(MDP.shape[2]))
            Q.append(q_sa)                    
            if q_sa < q_best:
                policy[s_k] = a
                q_best = q_sa
        try:    
            V[s_k] = min(Q)
        except:
            V[s_k] = 0


        #Parte C: para todo s diferente de s_k pertencente a S gere a nova função de prioridade Hk+1(s)
        #enquanto não atinge critério de parada
            
        delta = np.absolute(V[s_k] - Vold[s_k])
        for index_s in range(N_STATES):
            new_priority = max([delta * MDP[s_k, a, index_s] for a in range(N_ACTIONS)])
            if index_s != s_k:
                H[index_s] = max(H[index_s], new_priority)
            else:
                H[index_s] = new_priority
        

        numIter = numIter +  MDP.shape[1]

        
        list_V.append(str(V))
        list_policy.append(str(policy))
        if np.absolute(np.sum(V - Vold)) < epsilon and np.max(H) < epsilon:
            return V, policy, numIter, epoca, list_V, list_policy


        epoca +=1

In [12]:
V, politica, numIter, epoca, list_V, list_policy = prioritized_sweeping(P, R, 0.01, 1)

****** Epoca:  1
****** Epoca:  2
****** Epoca:  3
****** Epoca:  4
****** Epoca:  5
****** Epoca:  6
****** Epoca:  7
****** Epoca:  8
****** Epoca:  9
****** Epoca:  10
****** Epoca:  11
****** Epoca:  12
****** Epoca:  13
****** Epoca:  14
****** Epoca:  15
****** Epoca:  16
****** Epoca:  17
****** Epoca:  18
****** Epoca:  19
****** Epoca:  20
****** Epoca:  21
****** Epoca:  22
****** Epoca:  23
****** Epoca:  24
****** Epoca:  25
****** Epoca:  26
****** Epoca:  27
****** Epoca:  28
****** Epoca:  29
****** Epoca:  30
****** Epoca:  31
****** Epoca:  32
****** Epoca:  33
****** Epoca:  34
****** Epoca:  35
****** Epoca:  36
****** Epoca:  37
****** Epoca:  38
****** Epoca:  39
****** Epoca:  40
****** Epoca:  41
****** Epoca:  42
****** Epoca:  43
****** Epoca:  44
****** Epoca:  45
****** Epoca:  46
****** Epoca:  47
****** Epoca:  48
****** Epoca:  49
****** Epoca:  50
****** Epoca:  51
****** Epoca:  52
****** Epoca:  53
****** Epoca:  54
****** Epoca:  55
****** Epoca:  56
*

#### Solução esperada
array([6.99984741, 5.99919128, 3.99991989, 1.99999619, 0.        ,
       5.        , 4.        , 3.        , 2.        , 1.        ])

In [13]:
V

array([6.99830627, 5.93887329, 3.96777344, 1.984375  , 0.        ,
       5.        , 4.        , 3.        , 2.        , 1.        ])

### Política esperada
array([1., 2., 2., 2., 0., 2., 2., 2., 2., 0.])

In [14]:
politica

array([1., 2., 2., 2., 0., 2., 2., 2., 2., 0.])

In [15]:
numIter

364

In [16]:
epoca

91